### ISSUE TITLE
java.io.IOException: Failed to run image 'trion/ng-cli-karma'. Error: docker: Error response from daemon: grpc: the connection is unavailable.

### ISSUE THREAD

**Issue by C0ZEN** [trion-development/docker-ng-cli-karma#10]
I used another image (angular/ngcontainer) and this is working fine.
So the error seems really related to this one only.
I ran into this error yesterday at ~7pm Paris Tz.

**Comment by C0ZEN** [comment]
Nevermind, at some point the angular/ngcontainer image also fail.
This is not related.

**Comment by everflux** [comment]
This looks like you are using some kind of java based orchestration (testcontainers?) to launch a container. The grpc error suggests that the docker daemon is unreachable, perhaps a firewall issue, rate limit or if you are running windows or mac it might me a crash due to setting the memory of the docker vm too low.
Besides it sounds like you have an interesting setup, if you would like to share more details it might be inspirational and benefit others that use the angular image.

**Comment by C0ZEN** [comment]
@everflux Sorry but my knowledge of the Infra of this project is very limited.
We are using Jenkins by the way.

We had some problems with long-running dockers (dunno why though).

```
norsys@debian9-jenkins-slave-01:~$ docker ps -a
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS               NAMES
764b8b1039ca        angular/ngcontainer   "cat"               14 minutes ago      Created                                 condescending_meitner
74cd1135be5b        trion/ng-cli-karma    "cat"               27 minutes ago      Created                                 laughing_murdock
497be1cef9ee        trion/ng-cli-karma    "cat"               18 hours ago        Up 18 hours         4200/tcp            dazzling_bartik
4e9e9ffa5a80        trion/ng-cli-karma    "cat"               18 hours ago        Up 18 hours         4200/tcp            silly_lichterman
```

And that was pretty fucked up.
Unkillable beasts.

```
norsys@debian9-jenkins-slave-01:~$ docker stop dazzling_bartik
Error response from daemon: Cannot stop container dazzling_bartik: Cannot kill container 497be1cef9ee4c2bb5958f5020bd1b749930d995957af6322699f78ec3a77a2b: rpc error: code = 14 desc = grpc: the connection is unavailable
norsys@debian9-jenkins-slave-01:~$ docker stop silly_lichterman
Error response from daemon: Cannot stop container silly_lichterman: Cannot kill container 4e9e9ffa5a808632bb5c51b96226ba164324796a803c447d89e75fb1bf686464: rpc error: code = 14 desc = grpc: the connection is unavailable
norsys@debian9-jenkins-slave-01:~$ docker kill dazzling_bartik
Error response from daemon: Cannot kill container dazzling_bartik: Cannot kill container 497be1cef9ee4c2bb5958f5020bd1b749930d995957af6322699f78ec3a77a2b: rpc error: code = 14 desc = grpc: the connection is unavailable
norsys@debian9-jenkins-slave-01:~$ docker kill silly_lichterman
Error response from daemon: Cannot kill container silly_lichterman: Cannot kill container 4e9e9ffa5a808632bb5c51b96226ba164324796a803c447d89e75fb1bf686464: rpc error: code = 14 desc = grpc: the connection is unavailable
norsys@debian9-jenkins-slave-01:~$ sudo docker stop dazzling_bartik
```

Using `docker system prune` was a good work around.

All I can tell is that the Infra does not like huge projects with a lot of files or too long files - or paths and as a result some random errors occurred.

**Comment by everflux** [comment]
Thanks for sharing the information.
Seems to be a jenkins setup :)
Hard to tell what could cause loosing the docker connection when it is running for a long time.

Some of our customers experienced similar problems with orphaned containers when the build breaks. You might want to add a post build step to remove containers that kept running. You need to define the variable (ng-container in this case) in the right scope, so outside the 'pipeline' to be able to access it everywhere. (Assuming you are using a scripted pipeline and use .run() )

    post {
        always {
            script { 
                ng-container.stop()
            }
        }
    }

The other solution would be to use 

```
docker.image('trion/ng-cli-karma')
       .inside() { ... }

```
It should stop/remove the container after leaving the block automatically.

**Comment by C0ZEN** [comment]
@everflux I did not expected some help by posting the information so thank you for the feedback.
I had a talk with the Infra guys mostly to know if they know a way to "try catch" the docker image and stop it on error/when the duration is far beyond reasonable.
They did not provide a clue on how to manage that.

I am using a scripted pipeline.
Nevertheless I already use the "other solution" and yet here we are.

```
docker.image("trion/ng-cli-karma").inside("--entrypoint='' -e HOME=${userHome}") { ... }
```

**Comment by everflux** [comment]
You could of course run a separate job that periodically cleans up hanging docker containers. But this should not be needed in the first place.
What jenkins basically does it first launch a container with a command that just blocks (`cat`) to keep the container alive. Then a docker execute is performed inside the running container. When the `.inside` block is left it should terminate the cat command and therefore stop the container.
Since your root issue was a problem communicating with the docker daemon it might be related.
I am out of clues here without knowing more about the infrastructure (Especially how you spawn jenkins slaves and handle the docker daemon. The situation could be caused by a setup like docker-in-docker or jenkins-slave-in-docker with outside docker daemon access.)

Perhaps you might want to check that you run the latest jenkins release and docker pipeline plugin.

**Comment by C0ZEN** [comment]
@everflux Thank you for the hints.
I will promote this thread to my coworkers.

**Comment by everflux** [comment]
You're welcome. Let me know if I can be of any assistance! (Or if there is something I should add to the README regarding Jenkins integration)
