### ISSUE TITLE
Chrome version?

### ISSUE THREAD

**Issue by froodley** [trion-development/docker-ng-cli-karma#5]
Can you tell me any more about what version of Chrome we can expect to be installed?

We are locked to tag 6.0.8 of ng-cli-e2e because of issues upgrading to node 9

This caused an issue because of the update of ChromeDriver to 2.42 yesterday, which requires Chrome to be v68-70

The 6.0.8 tag of this image is downloading Chome 67.0.3396.79 (currently)

(What my boss really wants is for the versions of both Chrome and ChromeDriver to be locked at some specific version to avoid these kinds of incidents.)

**Comment by everflux** [comment]
This is indeed an unfortunate situation:
During image build the browser is installed, f.e. chrome latest.
But the webdriver is installed during npm-install which happens at a later point in time. This is the reason that we failed to provide a working alpine variant of this image, since we did not accomplish to bundle the webdriver compiled with musl-libc and prevent a later installation of a different version through Angular CLI.
So the tagged image versions will not change, it will ship the chrome version that was current at the point in time the tag was build, but your project moves in time and uses newer dependencies that do not work with the old browser.
There are not much choices how to solve this:
- you can update the image version (let me know what problems node 9 causes for you and I will look into it)
- you can use the dockerfile and build your own images using current chrome but older angular cli/node

**Comment by froodley** [comment]
Actually, this should be fine from my side.  If the version of Chrome is already baked into the layer, we can just make our current approach permanent:

```
docker ... trion/ng-cli-e2e:6.0.8 \
    ./node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome 2.41 && \
    ng e2e -a="${APP}"
```

...which completely locks versions of both Chrome and ChromeDriver as desired.

**Comment by everflux** [comment]
Does that approach work for you? When I last checked I could not prevent angular-cli to update to the latest webdriver.
If it works it would be cool, if you could make a PR against the README to document that for other users as well.

**Comment by froodley** [comment]
Sure

https://github.com/trion-development/docker-ng-cli-e2e/pull/6
